# Travis config file to build spk package
# Adapted from https://github.com/torrentalle/spksrc/tree/gogs-build
notifications:
  email: false

git:
  depth: 1

sudo: required
language: false

# Build environment configuration
env:
  global:
    - PKG=sabnzbd-testing
  matrix:
    - SYNOARCH=88f6281
    - SYNOARCH=alpine
    - SYNOARCH=armada370
    - SYNOARCH=armada375
    - SYNOARCH=armada38x
    - SYNOARCH=armadaxp
    - SYNOARCH=avoton
    - SYNOARCH=braswell
    - SYNOARCH=bromolow
    - SYNOARCH=cedarview
    - SYNOARCH=comcerto2k
    - SYNOARCH=evansport
    - SYNOARCH=monaco
    - SYNOARCH=ppc853x
    - SYNOARCH=qoriq
    - SYNOARCH=x64
    - SYNOARCH=x86

# spksrc docker image
services:
  - docker

before_install:
  - docker pull synocommunity/spksrc

# Build spk package
script:
  # Output is too verbose for TravisCI, so we hide it
  # Remove the ">/dev/null" part to debug!
  - docker run -it -v `pwd`:/spksrc synocommunity/spksrc /bin/bash -c "cd /spksrc && make setup && cd spk/$PKG && make arch-$SYNOARCH >/dev/null"
  # make arch-$SYNOARCH always return exit code 0. This line is to test if SPK has been build.
  - ls packages/${PKG}_${SYNOARCH}*.spk

deploy:
  provider: releases
  api_key:
    secure: XOiD22Q6dvngimq2Oh+ySVW0/vxrCsLfvDjomVlBLa69RYErFLqbaCwkVo7w+hMynfFgrV2eAed3Gwp+LFIysWBHAed4jlr54M0PNIpqNrOERUTpPcOwffi4onEp7GtBXgcEa3eNioFRCRon0RhWIWgzYcW2N8MQ3Btycq6x7A94Gck0vsmHsu34mQktzPXrHik/4oiXw2ukCzm13sOH21uOpeXP0oY/0qcIMXtDtE3vms3+RGeO5KF21vrZG2ffHBDokwNJHg8O5TORr9MS8lX4w7huvDa50EKWYk0Yw2w7Ko+aeOFhd85FVAs47KKhF3kLn0K7fuX1kC73Jo6+7TErpzi4LcAV5cU6ZMKLKeHLk18P1eDvhTG81KQP4DL9vNS0U0EkeUujlDWwC2atjf481jDzNhlgD9zzLuxMd8tenaKmiku9LSZMrlx3Yo9Tw9jB64MWDpravbgQOFhL3f8eLXkLPJbSu2to5HFNJVxerI18xM/PWCNGm4Xq6PEP5HY+0Ao8giNNsVzV0H5CiHFIfb2yUNNq+LPtrM8JjxuQYnbgsHhpJb82HIHPmoJ3KA3YrzDAwFZ29EcDOwlqHJZOrSlAEPLwmdn6s7oKvO22fsvAXXPO1L4oDS0AQcqyey6+2DjxoKMAmaOn4n7YaxHQaN6JmsaBoCKnG981WMo=
  file_glob: true
  file: packages/*.spk
  skip_cleanup: true
  overwrite: true
  on:
    tags: true