SPK_NAME = ffmpeg
SPK_VERS = 4.1
SPK_REV = 11
SPK_ICON = src/ffmpeg.png
CHANGELOG = "1. Update ffmpeg to 4.1 (latest release) 2. Update ffmpeg dependencies to latest release and fix associated compilation issues 3. Fix HDR10Plus support in x265 4. Fix x265 support for ppc platforms with recent releases"

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = cytec
DESCRIPTION = FFmpeg is a complete, cross-platform solution to record, convert and stream audio and video. It includes libavcodec - the leading audio/video codec library.
DISPLAY_NAME = ffmpeg
STARTABLE = no

HOMEPAGE = http://www.ffmpeg.org/
LICENSE  = GPLv3

include ../../mk/spksrc.spk.mk
